version: "3"

services:
  db:
    image: postgres:13.1
    env_file:
      - environment.env
    restart: always
    ports:
      - "5433:5432"
    healthcheck:
      test: "exit 0"
    volumes:
      - postgres:/var/lib/postgresql

  redis:
    image: redis:6.0
    restart: always
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    # ulimits:
    #   memlock:
    #     soft: -1
    #     hard: -1
    #   nofile:
    #     soft: 65536
    #     hard: 65536
    # cap_add:
    #   - IPC_LOCK
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  backend:
    image: priceindex-backend
    build: .
    entrypoint: /app/entrypoint.sh
    ports:
      - "8080:3000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - elasticsearch
    env_file:
      - environment.env
    restart: always

  sidekiq:
    image: priceindex-backend
    command: 'bundle exec sidekiq -e $RAILS_ENV'
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - backend
    env_file:
      - environment.env
    restart: always

volumes:
  postgres:
  elasticsearch:
  bundle_path:
