version: "3"

services:
  db:
    image: postgres:15.0
    env_file:
      - environment.env
    restart: always
    healthcheck:
      test: "exit 0"
    volumes:
      - postgres:/var/lib/postgresql

  redis:
    image: redis:6.0
    restart: always

  backend: 
    image: priceindex-backend
    build: .
    entrypoint: /app/entrypoint.sh
    ports:
      - "8080:3000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - environment.env
    restart: always
  
  sidekiq: 
    image: priceindex-backend
    command: 'bundle exec sidekiq -e $RAILS_ENV'
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - backend
    env_file:
      - environment.env
    restart: always

volumes:
  postgres:
  bundle_path: