json.id @product.id
json.name @product.name
json.price @product.price
json.description @product.description
json.image_url @product.image_url
json.url @product.url
json.source @product.source.name
json.status @product.status
json.category_id @product.category_id
json.prices @prices
