source_pages:
  cron: '0 */6 * * *' # At minute 0 past every 6th hour
  class: "SourcePagesCheckWorker"
  queue: default

products:
  cron: '*/1 * * * *' # At minute 0 past every 1 hour
  class: "ProductsCheckWorker"
  queue: default

delete_logs:
  crone: '0 0 * * *'
  class: "DeleteLogsWorker"
  queue: default