source_pages:
  cron: '0 */10 * * *' # At minute 0 past every 10th hour
  class: "SourcePagesCheckWorker"
  queue: default

products:
  cron: '0 */10 * * *' # At minute 0 past every 10th hour
  class: "ProductsCheckWorker"
  queue: default