source_pages:
  cron: '0 * * * *' # runs every minutes
  class: "SourcePagesCheckWorker"
  queue: default


products:
  cron: '0 * * * *' # runs every minutes
  class: "ProductsCheckWorker"
  queue: default