source_pages:
  cron: '0 */5 * * *' # runs every minutes
  class: "SourcePagesCheckWorker"
  queue: default


products:
  cron: '0 */5 * * *' # runs every minutes
  class: "ProductsCheckWorker"
  queue: default