queues:
  - default
  - source_page_scraper
  - product_details_scraper
  - product_score
  - low_priority

:limits:
  default: 2
  source_page_scraper: 2
  product_details_scraper: 4
  product_score: 1
  low_priority: 1

